@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1280719429 { 
   	label=Funcionario
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Funcionario1280719429[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Funcionario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   CPF: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cargo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1959718455 { 
   	label=PatrimonioIntangivel
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   PatrimonioIntangivel1959718455[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PatrimonioIntangivel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   tipo: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2104331723 { 
   	label=Filial
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Filial2104331723[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Filial</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   endereco: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   funcionarios: List&lt;Funcionario&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   patrimonios: List&lt;Patrimonio&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ adicionarFuncionario(funcionario: Funcionario)</TD></TR>
<TR><TD ALIGN="LEFT" >+ adicionarPatrimonio(patrimonio: Patrimonio)</TD></TR>
<TR><TD ALIGN="LEFT" >+ atualizarFuncionario(funcionario: Funcionario)</TD></TR>
<TR><TD ALIGN="LEFT" >+ atualizaraPatrimonio(patrimonio: Patrimonio)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getFuncionario(cpf: String): Optional&lt;Funcionario&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPatrimonio(descricao: String): Optional&lt;Patrimonio&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPatrimoniosByFuncionario(cpf: String): List&lt;Patrimonio&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ removerFuncionario(funcionario: Funcionario)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removerPatrimonio(patrimonio: Patrimonio)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_407591954 { 
   	label=PatrimonioTangivel
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   PatrimonioTangivel407591954[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PatrimonioTangivel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   altura: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   largura: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   profundidade: double [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_556721288 { 
   	label=Patrimonio
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Patrimonio556721288[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Patrimonio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   descricao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   funcionarioResponsavelCPF: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   valor: double [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Filial2104331723 -> Funcionario1280719429[label="funcionarios
[0..*]"];
Filial2104331723 -> Patrimonio556721288[label="patrimonios
[0..*]"];
Patrimonio556721288 -> PatrimonioIntangivel1959718455[arrowhead=none, arrowtail=empty, dir=both];
Patrimonio556721288 -> PatrimonioTangivel407591954[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml